/**
 * @description PURE IT 22/05 - commentata la classe
 */
public with sharing class getComuniResponse {
    /**PURE IT
    public getComuniResponse() {}
    
    public EsitoClass Esito;
    public list<TabLocalitaClass> TabLocalita;
    

    public with sharing class EsitoClass {
        public String CodiceEsito;
        public String DescrizioneEsito;
 
        public EsitoClass() {}
    }
    public with sharing class TabLocalitaClass {
        
        public String NumOccorrenza;
        public String TipoLocalitaUfficiale;
        public String DesTipoLocalitaUfficiale;
        public String SigProvin;
        public String CodLing;
        public String CAP;
        public String FlViarioNaz;
        public String FlViarioZon;
        public String CodStatistico;
        public String SigProvAmm;
        public String DesLocalitaAmm;
        public String CodStatisticoAmm;
        public String DesLocalitaRicerca;
        public String CAPRicerca;
        public String SigProRicerca;
        public String TipoElemento;
        public String FlSinonimo;
        public String DesTipoCertificazione;
        public String TipoCertificazione;
        public String DesRegione;
        public String CodRegione;
        public String DesProvin;
        public String DesLingua;
        public String DesLocalitaUff;
        public String DesLocalitaOut;
        public String DesLocalitaAbb;
        public String FlViarioSpe;
        public String CAPLocalitaAmm;
        public String TpDato;
        public String DesTpDato;
        public String FlTpDatoMultiplo;
        public String AttributoPrimario;
 
        public TabLocalitaClass() {}
    }
    

    public static getComuniResponse parse(String json) {
        return (getComuniResponse) System.JSON.deserialize(json, getComuniResponse.class);
    }
PURE IT */
}